In [1]:
import pandas as pd
import numpy as np
from ggplot import *
%matplotlib inline

In [2]:
df = pd.read_pickle('runHist.pkl')

In [7]:
df[:21]

,trip,light,oncoming,left,right,next_waypoint,action,qA,qV,reward,alpha,deadline,Explored
1001,1,green,None,None,None,forward,right,None,0,0.5,0.2,20,True
1002,1,green,None,None,None,left,forward,None,0,0.5,0.2,19,True
1003,1,green,None,None,None,left,left,forward,0.5,2,0.2,18,True
1004,1,green,None,None,None,forward,right,right,0.5,0.5,0.2,17,True
1005,1,red,None,None,None,left,None,None,0,1,0.2,16,True
1006,1,red,None,None,None,left,forward,None,1,-1,0.2,15,True
1007,1,red,None,None,None,left,None,None,1,1,0.2,14,True
1008,1,red,None,None,None,left,forward,None,1.2,-1,0.2,13,True
1009,1,green,None,None,None,left,right,left,2.1,0.5,0.2,12,True
1010,1,red,None,None,None,right,left,None,0,-1,0.2,11,True
1011,1,red,None,None,None,right,forward,None,0,-1,0.2,10,True
1012,1,red,None,None,None,right,None,None,0,1,0.2,9,True
1013,1,green,None,None,None,right,forward,None,0,0.5,0.2,8,True
1014,1,red,None,None,None,right,left,None,1,-1,0.2,7,True
1015,1,red,None,None,None,right,None,None,1,1,0.2,6,True
1016,1,green,None,None,None,right,None,forward,0.5,1,0.2,5,True
1017,1,green,None,None,None,right,forward,None,1.1,0.5,0.2,4,True
1018,1,red,None,None,None,right,forward,None,1.2,-1,0.2,3,True
1019,1,green,None,None,None,right,None,None,1.1,1,0.2,2,False
1020,1,green,None,None,None,right,left,None,1.22,0.5,0.2,1,True
1021,1,green,None,None,None,left,left,left,2.1,2,0.2,0,True

In [8]:
temp = df.groupby(['trip']).agg({'deadline':'max','trip':'count'})
temp['deadline']+=1
ggplot(temp, aes(x='Trip Number',y='Steps to Complete')) + geom_line() + ggtitle('Number of Steps to Complete a Trip over Time')

      deadline  trip
trip
1           21    21
2           31    31
3           21    21
4           26     8
5           26    26
6           26     9
7           36    19
8           21    21
9           41    29
10          31    30
11          51    50
12          26    14
13          36    22
14          31    19
15          41    10
16          41    21
17          36    36
18          46    27
19          26    16
20          51    25
21          36    14
22          26    17
23          31    10
24          36    21
25          31     6
26          46    29
27          46    25

In [58]:
tempq = df.groupby(['trip'])['reward']
tempq.mean()
#ggplot(tempq, aes(x='trip',y='reward')) + geom_line() #+ ggtitle('Number of Steps to Complete a Trip over Time')

DataError: No numeric types to aggregate